### ISSUE TITLE
keeper-cli error when running in redis:alpine

### ISSUE THREAD

**Issue by kevinmatspie** [Keeper-Security/secrets-manager#541]
The latest version of ksm (1.1.1) throws an exception when running in the redis:alpine container (and possibly others). We're using ksm in our docker-compose file to start redis via a shell script, using the "exec" command to replace an environment variable with the secret. We run the keeper/keeper-secrets-manager-cli:latest image first and the redis container executes /cli/musl/ksm and we see the following exception:
```[8] Failed to execute script ksm
Traceback (most recent call last):
  File "ksm.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "keeper_secrets_manager_cli/__init__.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "keeper_secrets_manager_core/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "keeper_secrets_manager_core/core.py", line 24, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "keeper_secrets_manager_core/utils.py", line 31, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "keeper_secrets_manager_core/keeper_globals.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "importlib_metadata/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "zipp/__init__.py", line 9, in <module>
ModuleNotFoundError: No module named 'zipp.py310compat'
```
This error does not occur in the 1.1.0 version.

**Comment by jwalstra-keeper** [comment]
keeper/keeper-secrets-manager-cli:1.1.1.2 or latest now have a fixed MUSL/Alpine CLI binary.
