### ISSUE TITLE
invalid client version id: 16, mp16.2.0

### ISSUE THREAD

**Issue by Sinan81** [Keeper-Security/secrets-manager#546]
We're currently testing keeper software. we ran into this issue, wondering what it means exactly. Did some google search but nothing came up. At the moment, we have to keep cryptography dependency version at 3.4.7, hence latest version of keeper manager we can use is 16.4.0. Wondering if this might be the issue, and if there is a workaround:
```
Traceback (most recent call last):
  File "./test_keeper.py", line 4, in <module>
    secret = manager.get_secrets(['XXXXXXXXXX'])[0]
  File "/disk/software/lib/python-venvs/keeper/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 650, in get_secrets
    records_resp = self.fetch_and_decrypt_secrets(uids)
  File "/disk/software/lib/python-venvs/keeper/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 567, in fetch_and_decrypt_secrets
    decrypted_response_bytes = self._post_query(
  File "/disk/software/lib/python-venvs/keeper/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 459, in _post_query
    self.handler_http_error(ksm_rs.http_response)
  File "/disk/software/lib/python-venvs/keeper/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 552, in handler_http_error
    raise err
  File "/disk/software/lib/python-venvs/keeper/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 545, in handler_http_error
    raise KeeperError(msg)
keeper_secrets_manager_core.exceptions.KeeperError: invalid client version id: 16, mp16.2.0
```

**Comment by Sinan81** [comment]
We're using canadian data center: keepersecurity.ca.  `keeper_secrets_manager_core` version is 16.4.0 and keeper version 1.1.1. According to documentation, this version of keeper_secrets_manager_core should support canadian data centers.

**Comment by Sinan81** [comment]
now, our code works. Thanks for the quick response.
