### ISSUE TITLE
Issues installing Jenkins plugin 

### ISSUE THREAD

**Issue by denis-accesa** [Keeper-Security/secrets-manager#551]
After updating to the latest Jenkins version, 2.439 and Java 21, I get the following error trying to install the plugin:

`java.lang.IllegalStateException: Refusing to load the Jenkins test harness in production (via keeper-secrets-manager)
	at hudson.ClassicPluginStrategy.createClassLoader(ClassicPluginStrategy.java:282)
	at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:238)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:928)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2249)
Caused: java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2253)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1899)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by jwalstra-keeper** [comment]
Fixed in version keeper-secrets-manager-1.0-87.v166c32650bd5. It is release, but might take an hour or so to appear in the updates.

**Comment by denis-accesa** [comment]
good morning, @jwalstra-keeper ! Thank you for the info and quick reply. Looking forward for the update.
