### ISSUE TITLE
java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CBC/PKCS7Padding

### ISSUE THREAD

**Issue by vvatov** [Keeper-Security/secrets-manager#555]
Hello,

I have exception when I am trying to get Folders:

`
java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CBC/PKCS7Padding
    	  at java.base/javax.crypto.Cipher.getInstance(Cipher.java:571)
    	  at com.keepersecurity.secretsManager.core.CryptoUtils.getCipher(CryptoUtils.kt:99)
    	  at com.keepersecurity.secretsManager.core.CryptoUtils.decrypt(CryptoUtils.kt:116)
    	  at com.keepersecurity.secretsManager.core.CryptoUtils.decrypt(CryptoUtils.kt:121)
    	  at com.keepersecurity.secretsManager.core.SecretsManager.fetchAndDecryptFolders(SecretsManager.kt:841)
    	  at com.keepersecurity.secretsManager.core.SecretsManager.getFolders(SecretsManager.kt:422)
    	  at com.aossia.cloud.xmob.automation.service.services.KeeperService.getFolders(KeeperService.java:180)
    	  at com.aossia.cloud.xmob.automation.service.AossiaCloudXMobKSMTests.folderTest(AossiaCloudXMobKSMTests.java:130)
    	  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    	  at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    	  at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
`

Java SDK
Maven:
    

    <dependency>
		      <groupId>com.keepersecurity.secrets-manager</groupId>
		      <artifactId>core</artifactId>
		      <version>16.6.2</version>
    </dependency>
OpenJDK 17.0.5+8

Thank you!

**Comment by vvatov** [comment]
Thank you for your quick response - the workaround works, but I'm facing a new exception:

javax.crypto.BadPaddingException: Error finalising cipher data: pad block corrupted
	at org.bouncycastle.jcajce.provider.BaseCipher.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2303)
	at com.keepersecurity.secretsManager.core.CryptoUtils.decrypt(CryptoUtils.kt:117)
	at com.keepersecurity.secretsManager.core.CryptoUtils.decrypt(CryptoUtils.kt:121)
	at com.keepersecurity.secretsManager.core.SecretsManager.fetchAndDecryptFolders(SecretsManager.kt:841)
	at com.keepersecurity.secretsManager.core.SecretsManager.getFolders(SecretsManager.kt:422)
	at com.aossia.cloud.xmob.automation.service.services.KeeperService.getFolders(KeeperService.java:200)
	at com.aossia.cloud.xmob.automation.service.AossiaCloudXMobKSMTests.folderTest(AossiaCloudXMobKSMTests.java:129)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

Thank you!

**Comment by vvatov** [comment]
A bit more info - getSecrets is working.

**Comment by vvatov** [comment]
Thank you!
I'll wait for the official release.
Thank yo again!

**Comment by vvatov** [comment]
Thank you!
I got v16.6.3 from Maven and it is working!
