### ISSUE TITLE
Different behaviour between different `ksm secret list` invocations

### ISSUE THREAD

**Issue by kript** [Keeper-Security/secrets-manager#575]
Hi folks,

Apologies if I am driving this wrong, but according to the [documentation](https://docs.keeper.io/secrets-manager/secrets-manager/secrets-manager-command-line-interface#create-a-local-client-device) there doesnt appear to be any difference between 
* `ksm secret init<TOKEN>; ksm secret list`
* `KSM_TOKEN="<TOKEN>" ksm secret list`

However when I run the former I get output;

```
$ ksm profile init <TOKEN>
$ ksm secret list

 UID                     Record Type Title
 ----------------------- ----------- -----
 0FC-kP1ggocbyjBdjSusUA  login       igs
```
but when I run the latter I get an error;
```
$ KSM_TOKEN="<TOKEN>" ksm secret list
ksm had a problem: Invalid base64-encoded string: number of data characters (45) cannot be 1 more than a multiple of 4
```

I am running 1.1.1;
```
$ pip freeze | grep keeper
keeper-secrets-manager-cli==1.1.1
keeper-secrets-manager-core==16.6.3
keeper-secrets-manager-helper==1.0.4
keeper-secrets-manager-storage==1.0.2
```

**Comment by flybyray** [comment]
Actually providing KSM_TOKEN via environment variable is not working.
But it should! ` KSM_TOKEN` 

> ```
> $ KSM_TOKEN="<TOKEN>" ksm secret list
> ksm had a problem: Invalid base64-encoded string: number of data characters (45) cannot be 1 more than a multiple of 4
> ```

I  used it with `KSM_TOKEN=EU:4Y1X....................................LRd0 ksm profile init` 
Same or similar error.

```
KSM_DEBUG=DEBUG KSM_TOKEN=EU:4Y1XAbwCKgtAZuMPSnKanjHtfwDV-P3bOXHA4iLLRd0 ksm secret list
Traceback (most recent call last):
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/__main__.py", line 1383, in main
    cli(obj={"cli": None}, prog_name=program_name)
  File "~/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "~/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/__main__.py", line 303, in cli
    "cli": _get_cli(
           ^^^^^^^^^
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/__main__.py", line 152, in _get_cli
    return KeeperCli(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/__init__.py", line 43, in __init__
    self.profile = Profile(cli=self, ini_file=ini_file, config=global_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/profile.py", line 55, in __init__
    Profile.init(
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/profile.py", line 133, in init
    client = KeeperCli.get_client(config=config_storage)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/secrets-manager/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/__init__.py", line 32, in get_client
    return SecretsManager(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/secrets-manager/sdk/python/core/keeper_secrets_manager_core/core.py", line 155, in __init__
    self._init()
  File "~/secrets-manager/sdk/python/core/keeper_secrets_manager_core/core.py", line 228, in _init
    existing_secret_key_bytes = url_safe_str_to_bytes(existing_secret_key)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/secrets-manager/sdk/python/core/keeper_secrets_manager_core/utils.py", line 99, in url_safe_str_to_bytes
    b = base64.urlsafe_b64decode(s + '==')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "/usr/lib64/python3.12/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (45) cannot be 1 more than a multiple of 4
```

**Comment by flybyray** [comment]
```shell
$ read -s KSM_TOKEN && ( echo  "$KSM_TOKEN" ) && unset KSM_TOKEN || unset KSM_TOKEN
test123
$ echo $KSM_TOKEN 

$ read -s KSM_TOKEN && ( ksm profile init  ) && unset KSM_TOKEN || unset KSM_TOKEN
Error: A one time access token is required either as a command parameter or an argument.
$ echo $KSM_TOKEN 

$ read -s KSM_TOKEN && ( export KSM_TOKEN ; ksm profile init  ) && unset KSM_TOKEN || unset KSM_TOKEN
ksm had a problem: Invalid base64-encoded string: number of data characters (45) cannot be 1 more than a multiple of 4
$ echo $KSM_TOKEN 

$ read -s KSM_TOKEN && ( ksm profile init --token $KSM_TOKEN ) && unset KSM_TOKEN || unset KSM_TOKEN
Payload: <keeper_secrets_manager_core.dto.payload.GetPayload object at 0x7f15cb84fce0>
Payload: <keeper_secrets_manager_core.dto.payload.GetPayload object at 0x7f15cb99baa0>
Added profile _default to INI config file located at /home/robert.rettig/ansible/keeper.ini
```
read lines input:
`1.`,: `test123`
`5.`,`9.`,`13.`,: `EU:token`

**Comment by flybyray** [comment]
Workarround or maybe this is the not documented correct way todo it.

```shell
$ read -s S_KSM_TOKEN && ( KSM_TOKEN=${S_KSM_TOKEN#*:} KSM_HOSTNAME=${S_KSM_TOKEN%%:*} ksm profile init  ) ; unset S_KSM_TOKEN
Payload: <keeper_secrets_manager_core.dto.payload.GetPayload object at 0x7ff1e89d3d10>
Payload: <keeper_secrets_manager_core.dto.payload.GetPayload object at 0x7ff1e9b7e030>
Added profile _default to INI config file located at ~/ansible/keeper.ini
Error: A one time access token is required either as a command parameter or an argument.
```

**Comment by flybyray** [comment]
Thanks for the update

> As a workaround currently you can use `--token` option _(working with both padded and unpadded tokens)_ ex. `ksm profile init --token=US:XXX`
Will wait for the KSM_TOKEN environment variable. Need it to document inital workflows. `read -s KSM_TOKEN` is still one of the preferred ways to inject data instead of command arguments. But yes it is a workarround.
